### ISSUE TITLE
Indentation for hash with lamdas

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/ruby-style#179]
How we have something like

```ruby
  @test = {
    test: lambda do |i|
            i
          end
  }
```

**Comment by paydaylight** [comment]
@roman-dubrovsky what do you think, `alignment` and `indentation` are two separate concepts that are present in rubocop cops. Would it be better to separate this cop into two cops: 
* cop that checks indentation of block internals for blocks in a hash
* cop that checks the alignment of `end` keyword for blocks in a hash

we can then set warnings if one of the cops is disabled as they should work together.
