### ISSUE TITLE
Style/FrozenStringLiteralComment

### ISSUE THREAD

**Issue by roman-dubrovsky** [datarockets/ruby-style#32]
Thought by this cop? 

https://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment

**Comment by AleksSenkou** [comment]
@roman-dubrovsky what value it can bring to us?

I feel like it +1 line in every file, nothing more 🤔

**Comment by TheBlackArroVV** [comment]
It's makes strings immutabl
https://stackoverflow.com/questions/37799296/what-does-the-comment-frozen-string-literal-true-do

**Comment by TheBlackArroVV** [comment]
But i don't really think it helps so much to live this comment in the top of file

**Comment by AleksSenkou** [comment]
Yeah, that's the thing. I don't think it's worth it.

**Comment by roman-dubrovsky** [comment]
read here https://freelancing-gods.com/2017/07/27/friendly-frozen-string-literals.html

This is just a performance improvement and fixes some issue with memory

**Comment by roman-dubrovsky** [comment]
@dzhlobo do you have any thoughts?

**Comment by AleksSenkou** [comment]
> This is just a performance improvement and fixes some issue with memory

@roman-dubrovsky yeah, it's clear. I just don't like this line at the beginning of a file. It damages the ability to read code faster for me. I don't mind to go with it anyway

**Comment by roman-dubrovsky** [comment]
>  It damages the ability to read code faster for me.

@AleksSenkou I agree that it looks annoying but I don't understand how `it damages the ability to read code faster`

**Comment by AleksSenkou** [comment]
@roman-dubrovsky I just used to see something useful at the very first line. Class/module definition or anything else, but not a helpless comment

**Comment by roman-dubrovsky** [comment]
🤷‍♂

**Comment by AleksSenkou** [comment]
Any ideas?

**Comment by dzhlobo** [comment]
My random thoughts.

It was planned to make all the string literals frozen by default in Ruby 3 but those plans were abandoned: https://bugs.ruby-lang.org/issues/11473#note-53. So we're sticking to those magic comments forever.

I'm not sure we will ever be able to enable freezing string literals application-wide due to gems compatibility issues.

It would be great to actually measure benefits we get when we add the magic comment to all the files in a rails app.

**Comment by roman-dubrovsky** [comment]
@dzhlobo @AleksSenkou looks like we can disable this cop for now and return to this issue later.
